name: FTP Deploy to Staging

on:
  push:
    branches:
      - main  # vagy a fő ágad neve

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub tároló klónozása
        uses: actions/checkout@v3

      - name: FTP feltöltés a staging mappába
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp://cpanel32.tarhelypark.hu
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Javítottuk: a helyi gyökérkönyvtár
          server-dir: /dagobertapp.com/staging/  # A távoli staging könyvtár
          dangerous-clean-slate: false
