name: FTP Deploy

on:
  push:
    branches:
      - main  # Ha a fő ágad neve más, írd át például "master"-re

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub tároló klónozása
        uses: actions/checkout@v3

      - name: FTP feltöltés
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp://ftp.yourserver.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .  # Ez a projekt gyökérkönyvtára
          dangerous-clean-slate: false  # Csak a módosított fájlokat tölti fel
